### PR TITLE
make relay-runtime a loose peerdep

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by taion** [comment]
What's the issue here? My motivation for this setup was that relay-runtime isn't a peer dep for Relay itself, and that hopefully npm can dedupe the dep anyway.

If you do explicitly install relay-runtime, then you can always just use `createFetch` directly and just copy https://github.com/relay-tools/relay-local-schema/blob/master/src/modern/Network.js yourself.

**Comment by graingert** [comment]
@taion the issue is that your old relay-runtime depends on an old relay-compiler which means when I upgrade to 1.5.0-rc.1 I get two relay-runtimes (one with invalid peerDeps)

**Comment by taion** [comment]
You're still going to get a peer dep warning though:
image

**Comment by graingert** [comment]
aww nuts.

**Comment by taion** [comment]
Done in #43 anyway

**Pull request closed without merging**
