### PR TITLE
Remove GraphQL and Relay from devDependencies; leave them in peerDependencies

### PR DESCRIPTION
**Pull request by steveluscher**
I think this is how you avoid having two instances of GraphQL (and hence schema errors).

### CODE REVIEW

**Comment by taion** [comment]
How are you hitting these? Is this via `npm link`?

**Comment by taion** [comment]
I don't really want to drop the dev dependencies since I'd need to add them back if/when I add tests. I think they'd only cause issues w/duplicate libraries if you `npm link`ed in this package rather than `npm install`ing it.

**Comment by steveluscher** [comment]
The way I understand it is that if the consumer of your network layer pulled in `graphql@0.4.x` and this network layer pulled in `graphql@0.4.y`, you'd end up with two instances in your app. Since the GraphQL validator depends on doing `instanceof` checks, every one would fail, and you'd be hosed.

Moving them to `peerDependencies` shouldn't affect your ability to test, I don't think.

**Comment by steveluscher** [comment]
I'm probably wrong about not affecting your ability to test, as of npm 3.

**Comment by taion** [comment]
@steveluscher 

`devDependencies` only get installed when you do an `npm install` in the project directory, though. If you do `npm i relay-local-schema`, you can verify that the only dependency that explicitly gets pulled in is the `babel-runtime` dependency.

The only way you end up with dev dependency conflicts is if you `npm link` in the package from a working directory with the dev dependencies installed, since then the installed `node_modules` get copied over.

**Comment by taion** [comment]
I've actually stopped using `npm link` for anything React-related, since I hit this for React proper whenever I try to do that.

**Pull request closed without merging**
